# Generated by Django 5.2.4 on 2025-08-09 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_offers/')),
                ('coins_required', models.PositiveIntegerField()),
                ('offer_type', models.CharField(choices=[('shop_offer', 'Shop Offer'), ('donor_gift', 'Donor Gift'), ('event_ticket', 'Event Ticket'), ('eco_reward', 'Eco Reward')], max_length=20)),
                ('location_name', models.CharField(max_length=255)),
                ('location_map_url', models.URLField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_spent', models.PositiveIntegerField()),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('voucher_code', models.CharField(max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='store.storeoffer')),
            ],
        ),
    ]
