# Generated by Django 5.1.3 on 2025-08-09 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redemption',
            options={'ordering': ['-redeemed_at']},
        ),
        migrations.AlterModelOptions(
            name='storeoffer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='redemption',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='storeoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='redemption',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
