# Generated by Django 5.2.4 on 2025-08-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_redemption_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redemption',
            name='status',
        ),
    ]
