# Generated by Django 5.1.3 on 2025-08-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_redemption_options_alter_storeoffer_options_and_more'),
        ('store', '0003_remove_redemption_status'),
    ]

    operations = [
    ]
