# Generated by Django 5.1.3 on 2025-08-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='initial_eco_coins',
            new_name='eco_coins_awarded',
        ),
        migrations.RemoveField(
            model_name='task',
            name='total_eco_coins_awarded',
        ),
        migrations.RemoveField(
            model_name='task',
            name='verified_eco_coins',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Recycling & Waste Management', 'Recycling & Waste Management'), ('Environmental Conservation', 'Environmental Conservation'), ('Community Engagement', 'Community Engagement'), ('Miscellaneous', 'Miscellaneous')], max_length=50),
        ),
    ]
