# Generated by Django 5.1.3 on 2025-08-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_rename_initial_eco_coins_task_eco_coins_awarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepost',
            name='location_map_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='issuepost',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
