# Generated by Django 5.1.3 on 2025-09-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issuepost_location_map_url_issuepost_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks'),
        ),
    ]
