# Generated by Django 5.1.3 on 2025-09-12 18:14

import issues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_task_proof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to=issues.models.task_image_upload_path),
        ),
    ]
