# Generated by Django 5.2.4 on 2025-10-05 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_task_proof_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepost',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuepost',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuepost',
            name='resolved_description',
            field=models.TextField(blank=True, help_text='Describe how the issue was resolved.', null=True),
        ),
        migrations.AddField(
            model_name='issuepost',
            name='resolved_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolved_issues/'),
        ),
    ]
