# Generated by Django 5.1.3 on 2025-08-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('public_works', 'Public Works Department'), ('water_supply', 'Water Supply Department'), ('waste_management', 'Waste Management Department'), ('electricity', 'Electricity Department')], max_length=50, null=True),
        ),
    ]
