# Generated by Django 5.2.4 on 2025-10-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_block_hash',
            field=models.CharField(blank=True, help_text="The block hash of the user's registration transaction.", max_length=64, null=True),
        ),
    ]
